services:
  localstack:
    container_name: retosca-localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"  # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services port range
    environment:
      # LocalStack configuration
      - SERVICES=s3,ec2,iam,lambda,apigateway,dynamodb,cloudformation,sts
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PERSISTENCE=0
      - LAMBDA_EXECUTOR=local
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      # Use volume instead of host tmp folder to avoid permission issues
      - LOCALSTACK_VOLUME_DIR=/var/lib/localstack
    volumes:
      - "localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - retosca-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  retosca:
    container_name: retosca-app
    image: xdaryamo/retosca:latest
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      # AWS configuration for LocalStack
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT_URL=http://localstack:4566
      # Terraform LocalStack configuration
      - TF_VAR_endpoint_url=http://localstack:4566
    networks:
      - retosca-network
    # Keep container running for manual execution
    tty: true
    stdin_open: true

networks:
  retosca-network:
    driver: bridge

volumes:
  localstack-data:
