# ReTOSCA Docker Compose
# Download this file and run: docker compose up
#
# Prerequisites: Docker and Docker Compose installed
# No repository cloning required!

services:
  # LocalStack - AWS services emulation
  localstack:
    image: localstack/localstack:latest
    container_name: retosca-localstack
    ports:
      - "4566:4566"  # LocalStack edge port
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-1
      - SERVICES=s3,ec2,iam,lambda,apigateway,dynamodb,rds,vpc,cloudformation
    volumes:
      - "retosca_localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Main ReTOSCA application
  retosca:
    image: xdaryamo/retosca:latest
    container_name: retosca-app
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-1
      - LOCALSTACK_HOST=localstack
    volumes:
      # Mount your Terraform files here
      - "${TERRAFORM_DIR:-./terraform}:/app/input"
      # Generated TOSCA files will appear here
      - "${OUTPUT_DIR:-./output}:/app/output"
      # Examples from the image (writable for tflocal temporary files)
      - "retosca_examples:/app/examples"
    working_dir: /app
    # No default command - use the run script or specify manually
    # Example: docker compose run retosca --source terraform:input output/result.yaml
    entrypoint: ["python", "-m", "src.main"]

  # Extract built-in examples to your local machine
  extract-examples:
    image: xdaryamo/retosca:latest
    container_name: retosca-examples
    volumes:
      # Examples will be copied to this directory
      - "${EXAMPLES_DIR:-./examples}:/app/local-examples"
    entrypoint: ["sh", "-c"]
    command:
      - |
        echo "🔄 Extracting examples to local directory..."
        cp -r /app/examples/* /app/local-examples/ 2>/dev/null || echo "ℹ️  Some examples may not be accessible"
        echo "✅ Examples extracted! Check your examples directory."
        echo "📁 Available examples:"
        find /app/local-examples -name "*.tf" | head -10
        if [ $(find /app/local-examples -name "*.tf" | wc -l) -gt 10 ]; then
          echo "   ... and more"
        fi

  # Validate generated TOSCA files
  validate:
    image: xdaryamo/retosca:latest
    container_name: retosca-validate
    volumes:
      # Mount directory containing TOSCA files to validate
      - "${OUTPUT_DIR:-./output}:/app/tosca:ro"
    entrypoint: ["/app/scripts/test-tosca.sh"]

  # Interactive shell for advanced usage
  shell:
    image: xdaryamo/retosca:latest
    container_name: retosca-shell
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-1
      - LOCALSTACK_HOST=localstack
    volumes:
      - "${TERRAFORM_DIR:-./terraform}:/app/input"
      - "${OUTPUT_DIR:-./output}:/app/output"
    working_dir: /app
    entrypoint: ["/bin/bash"]
    stdin_open: true
    tty: true

volumes:
  retosca_localstack_data:
    driver: local
  retosca_examples:
    driver: local

# Usage Examples:
# 1. Extract examples:
#    docker compose run --rm extract-examples
#
# 2. Process your Terraform files:
#    TERRAFORM_DIR=/path/to/your/terraform docker compose run --rm retosca --source terraform:input output/result.yaml
#
# 3. Validate generated TOSCA:
#    docker compose run --rm validate
#
# 4. Interactive shell:
#    docker compose run --rm shell
#
# 5. Start LocalStack (for debugging):
#    docker compose up localstack
