services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-1
    volumes:
      - "localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  retosca:
    image: xdaryamo/retosca:latest
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-1
      - LOCALSTACK_HOST=localstack
    volumes:
      # Automatically mount input and output directories
      - "${INPUT_DIR:-./input}:/app/input"
      - "${OUTPUT_DIR:-./output}:/app/output"
      # Note: /app/examples is already included in the Docker image
    working_dir: /app
    # No default command - user must specify what to do
    entrypoint: ["python", "-m", "src.main"]

  validate:
    image: xdaryamo/retosca:latest
    volumes:
      # Mount directory with TOSCA files to validate
      - "${OUTPUT_DIR:-./output}:/app/tosca:ro"
    entrypoint: ["/app/scripts/test-tosca.sh"]

  extract-examples:
    image: xdaryamo/retosca:latest
    volumes:
      # Mount local directory where examples will be copied
      - "${EXAMPLES_DIR:-./examples}:/app/local-examples"
    entrypoint: ["sh", "-c"]
    command: ["cp -r /app/examples/* /app/local-examples/ && echo '✅ Examples extracted to local directory!' && ls -la /app/local-examples/"]

volumes:
  localstack_data:
